import { IDictionary } from '../types';

export default {
	'Type something': 'Напишіть щось',
	// About
	'About Jodit': 'Про Jodit',
	'Jodit Editor': 'Редактор Jodit',
	'Free Non-commercial Version': 'Версія не для комерційного використання',
	'GNU General Public License, version 2 or later':
		'Загальна публічна ліцензія GNU (GPL), версія 2 або вище',

	'Jodit User\'s Guide': 'Jodit Керівництво користувача',
	'contains detailed help for using':
		'містить детальну інформацію по використанню',
	'For information about the license, please go to our website:':
		'Для отримання відомостей про ліцензію' +
		'перейдіть будь ласка на сайт:',
	'Buy full version': 'Придбати повну версію',
	'Copyright © XDSoft.net - Chupurnov Valeriy. All rights reserved.':
		'Авторскі права © XDSoft.net - Чупурнов Валерій. ' +
		'Всі права захищено.',

	// Toolbar
	Anchor: 'Анкор',
	'Open in new tab': 'Відкрити посилання у новій вкладці',
	'Open editor in fullsize': 'Розгорнути редактор в повний розмір',
	'Clear Formatting': 'Очистити форматування',
	'Fill color or set the text color': 'Колір заливки або колір тексту',
	Redo: 'Повтор',
	Undo: 'Відміна',
	Bold: 'Жирний',
	Italic: 'Курсив',
	'Insert Unordered List': 'Вставка маркованого списку',
	'Insert Ordered List': 'Вставка нумерованого списку',
	'Align Center': 'Вирівняти по центру',
	'Align Justify': 'Вирівняти по ширині',
	'Align Left': 'Вирівняти по лівому краю',
	'Align Right': 'Вирівняти по правому краю',
	'Insert Horizontal Line': 'Вставити горизонтальну лінію',
	'Insert Image': 'Додати зображення',
	'Insert file': 'Додати файл',
	'Insert youtube/vimeo video': 'Додати відео',
	'Insert link': 'Додати посилання',
	'Font size': 'Размір шрифту',
	'Font family': 'Шрифт',

	'Insert format block': 'Вставити блочний елемент',
	Normal: 'Нормальний текст',
	'Heading 1': 'Заголовок 1',
	'Heading 2': 'Заголовок 2',
	'Heading 3': 'Заголовок 3',
	'Heading 4': 'Заголовок 4',
	Quote: 'Цитата',
	Code: 'Код',

	Insert: 'Вставити',
	'Insert table': 'Додати таблицу',

	'Decrease Indent': 'Зменшити відступ',
	'Increase Indent': 'Збільшити відступ',
	'Select Special Character': 'Оберіть спеціальний символ',
	'Insert Special Character': 'Вставте спеціальний символ',

	'Paint format': 'Формат фарби',
	'Change mode': 'Джерело',

	// plugin Image
	Margins: 'Відступи',
	top: 'зверху',
	right: 'зправа',
	bottom: 'знизу',
	left: 'зліва',
	Styles: 'Стилі',
	Classes: 'Класи',
	Align: 'Вирівнювання',
	Right: 'По правому краю',
	Center: 'По центру',
	Left: 'По лівому краю',
	'--Not Set--': '--не встановлювати--',
	Src: 'src',
	Title: 'Заголовок',
	Alternative: 'Альтернативний текст (alt)',
	Link: 'Посилання',
	'Open link in new tab': 'Відкривати посилання в новому вікні',
	file: 'Файл',
	Advanced: 'Розширені',
	'Image properties': 'Налаштування зображення',
	Cancel: 'Відміна',
	Ok: 'Ок',

	// plugin paste
	'Your code is similar to HTML. Keep as HTML?':
		'Текст, який ви намагаєтесь вставить схожий на HTML. ' +
		'Вставити його як HTML?',
	'Paste as HTML': 'Вставити як HTML?',
	Keep: 'Зберегти оригінал',
	Clean: 'Очистити',
	'Insert as Text': 'Вставити як текст',
	'Insert only Text': 'Вставити лише текст',
	'Word Paste Detected': 'Можливо це фрагмент Word або Excel',
	'The pasted content is coming from a Microsoft Word/Excel document. Do you want to keep the format or clean it up?':
		'Контент, який ви вставляєте походить з документа Microsoft Word / Excel. Ви бажаєте зберегти ' +
		'формат чи очистити його?',

	// File Browser module
	'File Browser': 'Менеджер файлів',
	'Error on load list': 'Помилка під час завантаження списку зображень',
	'Error on load folders': 'Помилка під час завантаження списку директорій',
	'Are you sure?': 'Ви впевнені?',
	'Enter Directory name': 'Введіть назву директорії',
	'Create directory': 'Створити директорію',
	'type name': 'введіть назву',

	// Form module
	'Drop image': 'Перемістіть сюди зображення',
	'Drop file': 'Перемістіть сюди файл',
	'or click': 'або натисніть',
	'Alternative text': 'Альтернативний текст',
	Browse: 'Сервер',
	Upload: 'Вивантаження',

	Background: 'Фон',
	Text: 'Текст',

	// popap module
	Top: ' Доверху',
	Middle: 'По середині',
	Bottom: 'Донизу',
	'Insert column before': 'Додати стовпець перед',
	'Insert column after': 'Додати стовпець після',
	'Insert row above': 'Додати рядок вище',
	'Insert row below': 'Додати рядок нище',
	'Delete table': 'Видалити таблицю',
	'Delete row': 'Видалити рядок',
	'Delete column': 'Видалити стовпець',
	'Empty cell': 'Очистити клітинку',

	source: 'HTML',
	bold: 'жирний',
	italic: 'курсив',
	brush: 'заливка',
	link: 'посилання',
	undo: 'відмінити',
	redo: 'повторити',
	table: 'таблиця',
	image: 'Зображення',
	eraser: 'очистити',
	paragraph: 'параграф',
	fontsize: 'размір шрифту',
	video: 'відео',
	font: 'шрифт',
	about: 'про редактор',
	print: 'друк',
	symbol: 'символ',
	underline: 'підкреслити',
	strikethrough: 'закреслити',
	indent: 'відступ',
	outdent: 'виступ',
	fullsize: 'на весь екран',
	shrink: 'звичайний розмір',
	copyformat: 'Копіювати формат',
	hr: 'лінія',
	ul: 'Список',
	ol: 'Нумерований список',
	cut: 'Вирізати',
	selectall: 'Виділити все',
	'Embed code': 'Код',
	'Open link': 'Відкрити посилання',
	'Edit link': 'Редагувати посилання',
	'No follow': 'Атрибут nofollow',
	Unlink: 'Видалити посилання',
	Eye: 'Перегляд',
	pencil: 'Редагувати',
	Update: 'Обновити',
	' URL': 'URL',
	Edit: 'Редагувати',
	'Horizontal align': 'Горизонтальне вирівнювання',
	Filter: 'Фільтр',
	'Sort by changed': 'За змінами',
	'Sort by name': 'За іменем',
	'Sort by size': 'За розміром',
	'Add folder': 'Додати папку',
	Reset: 'Відновити',
	Save: 'Зберегти',
	'Save as ...': 'Зберегти як',
	Resize: 'Змінити розмір',
	Crop: 'Обрізати розмір',
	Width: 'Ширина',
	Height: 'Висота',
	'Keep Aspect Ratio': 'Зберігати пропорції',
	Yes: 'Так',
	No: 'Ні',
	Remove: 'Видалити',
	Select: 'Виділити',

	// stat
	'Chars: %d': 'Символів: %d',
	'Words: %d': 'Слів: %d',

	All: 'Віділити все',
	'Select %s': 'Виділити: %s',
	'Select all': 'Виділити все',

	'Vertical align': 'Вертикальне вирівнювання',
	Split: 'Розділити',
	'Split vertical': 'Розділити по вертикалі',
	'Split horizontal': 'Розділити по горизонталі',
	Merge: 'Об\'єднати в одну',
	'Add column': 'Додати стовпець',
	'Add row': 'Додати рядок',
	Delete: 'Видалити',
	Border: 'Рамка',
	'License: %s': 'Ліцензія: %s',
	'Strike through': 'Закреслити',
	Underline: 'Підкреслити',
	superscript: 'верхній індекс',
	subscript: 'індекс',
	'Cut selection': 'Вирізати',
	Break: 'Розділити',
	'Search for': 'Знайти',
	'Replace with': 'Замінити на',
	Replace: 'Замінити',
	Paste: 'Вставити',
	'Choose Content to Paste': 'Вибрати контент для вставлення',
	'You can only edit your own images. Download this image on the host?':
		'Ви можете редагувати лише власні ' +
		'зображення. Завантажити це зображення на ваш сервер?',
	'The image has been successfully uploaded to the host!':
		'Зображення успішно завантажено на сервер!',
	palette: 'палітра',
	'There are no files': 'Цей каталог не містить файлів',
	rename: 'Перейменувати',
	'Enter new name': 'Введіть нове ім\'я',
	preview: 'Попередній перегляд',
	download: 'Завантажити',
	'Paste from clipboard': 'Вставити з буфера обміну',
	'Your browser doesn\'t support direct access to the clipboard.': 'Ваш браузер не підтримує прямий доступ до буфера обміну.',
	'Copy selection': 'Скопіювати виділене',
	'copy': 'копія',
	'Border radius': 'Радіус краю',
} as IDictionary<string>;
